[package]
name = "generate-libkrun-measurment"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.107"
serde_json = "1.0.39"
serde = "1.0.90"
serde_derive = "1.0.90"
clap = "2"
